spring:
  application:
    name: ms-dashboard
  zipkin:
    base-url: http://localhost:9411
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/waliki
    username: mysql
    password: mysql
  data:
    rest:
      base-path: /api
      detection-strategy: ANNOTATED
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
###
allowed:
  origins: https://localhost:4200
###
server:
  port: 9030
  ssl:
    enabled: true
    key-alias: luv2code
    key-store: classpath:luv2code-keystore.p12
    key-store-password: secret
    key-store-type: PKCS12
###
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      ##defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      defaultZone: http://localhost:8761/eureka/
###
okta:
  oauth2:
    client-id: 0oa4x6ft4elsn2lJQ5d7
    client-secret: BYfZe5fTkL9BIoveFMTlrtIowruKmeI5lcFTZWz-
    issuer: https://dev-42801062.okta.com/oauth2/default
